#!/bin/bash

handle_login() {
    # simulate for async
    sleep 3
    echo "{\"user\": \"Kissa\", \"tokenValidUntil\": \"$(date -d tomorrow)\"}"
}

handle_logout() {
    echo "Logged out"
}

handle_list() {
    echo "["
    echo '  "Ohjelmointi 2",'
    echo '  "Algoritmit 1",'
    echo '  "Kissa istuu"'
    echo "]"
}

handle_pull() {
    echo "to be implemented"
}

handle_push() {
    echo "to be implemented"
}

handle_undefined() {
    echo "Unknown command: $1"
}

case $1 in
    "login")
        handle_login
        ;;
    "logout")
        handle_logout
        ;;
    "list")
        handle_list "$1"
        ;;
    "pull")
        handle_pull "$1" "$2"
        ;;
    "push")
        handle_push "$1" "$2"
        ;;
    *)
        handle_undefined "$1"
        ;;
    esac
