name: Tests

on:
  pull_request:
  push:
    branches:
      -'**'
jobs:
  run-all-tests:
    name: Run vscode-test and vitest for svelte-files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 23.7.0
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'
          cache: 'npm'

      - name: Upgrade to npm 11.1.0
        run: npm install -g npm@11.1.0

      - name: Confirm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Run vscode-test
        run: xvfb-run -a npm run test
      
      - name: Run vitest for svelte-files
        run: xvfb-run -a npm run test:svelte
